import { Clinic } from './types';

export const clinics: Clinic[] = [
  {
    id: 1,
    name: 'Sunrise Medical Center',
    type: 'General Practice',
    location: 'Los Angeles, CA',
    phone: '(555) 123-4567',
    email: 'contact@sunrisemedical.com',
    status: 'active',
    activePlans: 45,
    revenue: '125K',
    joinDate: '2023-01-15',
    rating: 4.8,
    reviews: 127,
    patients: 1250,
    growth: '+12.5%'
  },
  {
    id: 2,
    name: 'Valley Health Clinic',
    type: 'Family Medicine',
    location: 'Phoenix, AZ',
    phone: '(555) 234-5678',
    email: 'info@valleyhealth.com',
    status: 'paused',
    activePlans: 32,
    revenue: '89.5K',
    joinDate: '2023-03-22',
    rating: 4.6,
    reviews: 89,
    patients: 890,
    growth: '+8.2%'
  },
  {
    id: 3,
    name: 'Metro Dental Care',
    type: 'Dental',
    location: 'Denver, CO',
    phone: '(555) 345-6789',
    email: 'hello@metrodental.com',
    status: 'discontinued',
    activePlans: 28,
    revenue: '67.8K',
    joinDate: '2023-02-10',
    rating: 4.9,
    reviews: 65,
    patients: 650,
    growth: '-2.1%'
  },
  {
    id: 4,
    name: 'Family Health Partners',
    type: 'Pediatrics',
    location: 'Austin, TX',
    phone: '(555) 456-7890',
    email: 'support@familyhealth.com',
    status: 'active',
    activePlans: 0,
    revenue: '0',
    joinDate: '2024-01-08',
    rating: 4.2,
    reviews: 15,
    patients: 0,
    growth: '0%'
  },
  {
    id: 5,
    name: 'Westside Cardiology',
    type: 'Cardiology',
    location: 'San Diego, CA',
    phone: '(555) 567-8901',
    email: 'admin@westsidecardio.com',
    status: 'active',
    activePlans: 67,
    revenue: '198.4K',
    joinDate: '2022-11-30',
    rating: 4.7,
    reviews: 210,
    patients: 2100,
    growth: '+15.7%'
  },
  {
    id: 6,
    name: 'Northwood Psychiatry',
    type: 'Psychiatry',
    location: 'Seattle, WA',
    phone: '(555) 678-9012',
    email: 'contact@northwoodpsy.com',
    status: 'paused',
    activePlans: 18,
    revenue: '45K',
    joinDate: '2023-06-01',
    rating: 4.5,
    reviews: 40,
    patients: 450,
    growth: '+5.1%'
  },
  {
    id: 7,
    name: 'Coastal Orthopedics',
    type: 'Orthopedics',
    location: 'Miami, FL',
    phone: '(555) 789-0123',
    email: 'info@coastalortho.com',
    status: 'active',
    activePlans: 55,
    revenue: '150K',
    joinDate: '2022-09-10',
    rating: 4.9,
    reviews: 180,
    patients: 1800,
    growth: '+10.0%'
  },
  {
    id: 8,
    name: 'Peak Performance Sports Medicine',
    type: 'Sports Medicine',
    location: 'Denver, CO',
    phone: '(555) 890-1234',
    email: 'admin@peakperform.com',
    status: 'discontinued',
    activePlans: 10,
    revenue: '25K',
    joinDate: '2023-04-18',
    rating: 4.3,
    reviews: 20,
    patients: 200,
    growth: '-8.0%'
  },
  {
    id: 9,
    name: 'Green Valley Dermatology',
    type: 'Dermatology',
    location: 'Portland, OR',
    phone: '(555) 901-2345',
    email: 'hello@greenvalleyderm.com',
    status: 'active',
    activePlans: 38,
    revenue: '95K',
    joinDate: '2023-07-25',
    rating: 4.7,
    reviews: 90,
    patients: 950,
    growth: '+7.3%'
  },
  {
    id: 10,
    name: 'City Center Urgent Care',
    type: 'Urgent Care',
    location: 'Chicago, IL',
    phone: '(555) 012-3456',
    email: 'care@citycenteruc.com',
    status: 'active',
    activePlans: 70,
    revenue: '210K',
    joinDate: '2022-10-05',
    rating: 4.6,
    reviews: 250,
    patients: 2500,
    growth: '+18.0%'
  }
];
