import { PaymentPlan } from './types';

export const payments: PaymentPlan[] = [
  {
    id: 'PMT-001',
    patientName: 'John Smith',
    clinicName: 'Sunrise Medical Center',
    amount: 2400,
    installments: { current: 3, total: 12 },
    status: 'active',
    nextPayment: '2024-02-15',
    createdAt: '2024-01-10',
    procedure: 'Dental Implant',
    patientEmail: 'john.smith@email.com',
    patientPhone: '(555) 123-4567',
    patientAddress: '123 Main St, Los Angeles, CA 90210',
    monthlyAmount: 200,
    interestRate: 0,
    downPayment: 0
  },
  {
    id: 'PMT-002',
    patientName: 'Sarah Johnson',
    clinicName: 'Valley Health Clinic',
    amount: 1800,
    installments: { current: 6, total: 8 },
    status: 'active',
    nextPayment: '2024-02-20',
    createdAt: '2023-12-05',
    procedure: 'Orthodontic Treatment',
    patientEmail: 'sarah.johnson@email.com',
    patientPhone: '(555) 234-5678',
    patientAddress: '456 Oak Ave, Phoenix, AZ 85001',
    monthlyAmount: 225,
    interestRate: 3.5,
    downPayment: 200
  },
  {
    id: 'PMT-003',
    patientName: 'Michael Davis',
    clinicName: 'Metro Dental Care',
    amount: 850,
    installments: { current: 4, total: 4 },
    status: 'completed',
    nextPayment: null,
    createdAt: '2023-10-15',
    procedure: 'Root Canal',
    patientEmail: 'michael.davis@email.com',
    patientPhone: '(555) 345-6789',
    patientAddress: '789 Pine St, Denver, CO 80202',
    monthlyAmount: 212.50,
    interestRate: 0,
    downPayment: 0
  },
  {
    id: 'PMT-004',
    patientName: 'Emma Wilson',
    clinicName: 'Family Health Partners',
    amount: 3200,
    installments: { current: 1, total: 16 },
    status: 'overdue',
    nextPayment: '2024-01-30',
    createdAt: '2024-01-01',
    procedure: 'Surgical Procedure',
    patientEmail: 'emma.wilson@email.com',
    patientPhone: '(555) 456-7890',
    patientAddress: '321 Elm Dr, Austin, TX 73301',
    monthlyAmount: 200,
    interestRate: 5.9,
    downPayment: 500
  },
  {
    id: 'PMT-005',
    patientName: 'David Brown',
    clinicName: 'Westside Cardiology',
    amount: 5500,
    installments: { current: 8, total: 20 },
    status: 'active',
    nextPayment: '2024-02-25',
    createdAt: '2023-08-12',
    procedure: 'Cardiac Surgery',
    patientEmail: 'david.brown@email.com',
    patientPhone: '(555) 567-8901',
    patientAddress: '654 Cedar Ln, San Diego, CA 92101',
    monthlyAmount: 275,
    interestRate: 2.9,
    downPayment: 1000
  }
];
