# .github/workflows/linear-from-pr.yml
name: Linear on labeled PRs

on:
  pull_request:
    types: [labeled]  # runs when any label is added

permissions:
  pull-requests: write  # so the action can update PR title/comment

jobs:
  create-linear:
    if: ${{ github.event.label.name == 'needs-linear' }}  # guard by your label
    runs-on: ubuntu-latest
    steps:
      - uses: ctriolo/action-find-or-create-linear-issue@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}     # auto-provided
          linear-api-key: ${{ secrets.LINEAR_API_KEY }} # you added in step 2
          linear-team-key: ${{ secrets.LINEAR_TEAM_KEY }} # or hardcode e.g. ENG
